2019-07-10 15:38:51,455 ERROR: Exception on /user/Michael [GET] [in /Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michael/PycharmProjects/microblog/app/routes.py", line 94, in user
    next_url = url_for('/user/<username>', page=posts.next_num) if posts.has_next else None
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint '/user/<username>' with values ['page']. Did you mean 'user' instead?
2019-07-10 15:39:46,353 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:43]
2019-07-10 15:42:11,824 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:43]
2019-07-10 15:42:32,724 ERROR: Exception on /user/Michael [GET] [in /Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michael/PycharmProjects/microblog/app/routes.py", line 94, in user
    next_url = url_for('user', page=posts.next_num) if posts.has_next else None
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2080, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/helpers.py", line 345, in url_for
    force_external=external)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/werkzeug/routing.py", line 2007, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['page']. Did you forget to specify values ['username']?
2019-07-10 15:44:24,533 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:43]
2019-07-10 16:05:28,502 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:45]
2019-07-10 16:06:18,023 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:45]
2019-07-10 16:07:45,362 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:45]
2019-07-10 16:13:49,939 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:45]
2019-07-10 16:21:08,637 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:45]
2019-07-10 16:21:26,402 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:45]
2019-07-11 11:18:53,914 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:45]
2019-07-11 11:28:15,162 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:45]
2019-07-11 14:28:05,765 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:47]
2019-07-11 14:44:29,039 INFO: Microblog startup [in /Users/michael/PycharmProjects/microblog/app/__init__.py:49]
2019-07-11 14:47:29,607 ERROR: Exception on /explore [GET] [in /Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/michael/PycharmProjects/microblog/app/routes.py", line 53, in explore
    next_url=next_url, prev_url=prev_url)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/michael/PycharmProjects/microblog/app/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/michael/PycharmProjects/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/michael/PycharmProjects/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/michael/PycharmProjects/microblog/app/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/michael/PycharmProjects/microblog/app/templates/index.html", line 11, in block "app_content"
    {% include '_post.html' %}
  File "/Users/michael/PycharmProjects/microblog/app/templates/_post.html", line 5, in top-level template code
    <img src="{{ post.author.avatar(70) }}" />
jinja2.exceptions.UndefinedError: 'None' has no attribute 'avatar'
